apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mspr-ci-front-ingress
  namespace: prod-mspr-ci
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  rules:
  - host: front.louisperdereau.fr
    http:
      paths:
      - path: /
        backend:
          serviceName: mspr-ci-front-service
          servicePort: 80