kind: pipeline
type: kubernetes
name: default

steps:
  - name: install_dependencies
    image: node:12
    commands:
      - npm ci
  - name: lint
    image: node:12
    commands:
      - npm run lint
    depends_on: [install_dependencies]
  - name: test_unit
    image: node:12
    commands:
      -  NODE_ENV=test npm run test:unit
    depends_on: [lint]
  - name: test_e2e
    image: cypress/included:3.8.3
    commands:
      - NODE_ENV=test npm run test:e2e
    depends_on: [lint]
  - name: build
    image: node:12
    commands:
      -  npm run build
    depends_on: [test_unit,test_e2e]
  - name: docker
    image: banzaicloud/drone-kaniko
    settings:
      email: kedketh@gmail.com
      dockerfile: ./Dockerfile
      registry: docker.pkg.github.com
      repo:  ked57/mspr-ci-front/front
      username:
        from_secret: GITHUB_USERNAME
      password:
        from_secret: GITHUB_TOKEN
      tags:
        - ${DRONE_TAG}
        - latest
    when:
      event: tag
    depends_on: [build]
  - name: deploy
    image: pabloclsn/kubectl-docker:latest
    commands:
      - echo $KUBE_CONFIG > ~/.kube/config
      - cat .kube/deployment.yaml | envsubst | kubectl apply -f -
      - kubectl rollout restart deployment/mspr-ci-front-deployment -n prod-mspr-ci
    environment:
      KUBE_CONFIG:
        from_secret: KUBE_CONFIG
    when:
      event: tag
    depends_on: [docker]